//
//  03272017_animations.swift
//
//
//  Created by William Erbil on 3/27/17.
//
//

import Foundation
import Darwin

func clearScreen() {
    Process.launchedProcess(launchPath: "/usr/bin/clear", arguments: []).waitUntilExit()
}

clearScreen()
print("Hello")

sleep(2)
clearScreen()

sleep(3)
clearScreen()

print("Welcome to JAsciiws!")

sleep(3)
clearScreen()

print("Here is Jimmy on a boat.")

print("                                   ┌───┐                           ")
print("                                   │   │                           ")
print("                                   └─┬─┘                           ")
print("                                ┌┬┬──┴──┬┬┐                        ")
print("                                │││     │││                        ")
print("                                │││     │││                        ")
print("                                │││     │││                        ")
print("                                │││     │││                        ")
print("                                ││└──┬──┘││                        ")
print("                                └┘   │   └┘                        ")
print("                       .─────────────┴─────────────.               ")
print("                 _.───'                             `────.         ")
print("                 `─────.                           _.────'         ")
print("                        `─────────────────────────'                ")

sleep(5)
clearScreen()

print("He's really into fish, in fact he loves them fishes.")

sleep(3)
clearScreen()

print("Jimmy is out on a fishing trip, so here's him casting his fishing rod.")

sleep(3)
clearScreen()

print("                         ┌┬───────────────────────────────────────┐                ")
print("                         ││                                       │                ")
print("                         ││                                       │                ")
print("                   ┌───┐ ││                                       │                ")
print("                   │   │ ││                                       │                ")
print("                   └─┬─┘ ││                                       │                ")
print("                ┌┬┬──┴──┬┴┘                                       │                ")
print("                │││     │                                         │      .─────. . ")
print("                │││     │                                         └─────(       ( )")
print("                │││     │                                                `─────' ' ")
print("                │││     │                                                          ")
print("                ││└──┬──┘                                                          ")
print("                └┘   │                                                             ")
print("       .─────────────┴─────────────.                                               ")
print(" _.───'                             `────.                                         ")
print("(                                         )                                        ")
print(" `─────.                           _.────'                                         ")
print("        `─────────────────────────'                                                ")

sleep(1)
clearScreen()

print("                             ┌─────────────────┬┐                 ")
print("                             │                 ││                 ")
print("                             │                 ││                 ")
print("                             │           ┌───┐ ││                 ")
print("                             │           │   │ ││                 ")
print("                             │           └─┬─┘ ││                 ")
print("                             │        ┌┬┬──┴──┬┴┘                 ")
print("  . .─────.                  │        │││     │                   ")
print(" ( )       )─────────────────┘        │││     │                   ")
print("  ' `─────'                           │││     │                   ")
print("                                      │││     │                   ")
print("                                      ││└──┬──┘                   ")
print("                                      └┘   │                      ")
print("                             .─────────────┴─────────────.        ")
print("                       _.───'                             `────.  ")
print("                      (                                         ) ")
print("                       `─────.                           _.────'  ")
print("                              `─────────────────────────'         ")

sleep(1)
clearScreen()

print(" ")
print("                                     ┌──────────────────────────┬┐                 ")
print("                                     │                          ││                 ")
print("                                     │                          ││                 ")
print("                                     │                    ┌───┐ ││                 ")
print("                                     │                    │   │ ││                 ")
print("                                     │                    └─┬─┘ ││                 ")
print("                                     │                 ┌┬┬──┴──┬┴┘                 ")
print("                                     │                 │││     │                   ")
print("                                     │                 │││     │                   ")
print("                                     │                 │││     │                   ")
print("                                     │                 │││     │                   ")
print("                                     │                 ││└──┬──┘                   ")
print("                                     │                 └┘   │                      ")
print("                                     │        .─────────────┴─────────────.        ")
print("                                     │  _.───'                             `────.  ")
print("                                     │ (                                         ) ")
print("                                     │  `─────.                           _.────'  ")
print("                                     │         `─────────────────────────'         ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("  . .─────.                          │                                             ")
print(" ( )       )─────────────────────────┘                                             ")
print("  ' `─────'                                                                        ")

sleep(8)
clearScreen()

print("It was the best of times, it was the worst of times.")

sleep(3)
clearScreen()

print("Jimmy was not catching any fish.")

sleep(3)
clearScreen()

print("So, he decided to check Facebook and start livestreaming himself.")

sleep(5)
clearScreen()

print("  ┌────────────────────────────────┐                                                  ")
print("  │                                │                                                  ")
print("  │   ┌─────────────────────────┐  │                                                  ")
print("  │   │ ┌─────────────────────┐ │  │                                                  ")
print("  │   │ │    Facebook Live    │ │  │                                                  ")
print("  │   │ └─────────────────────┘ │  │                                                  ")
print("  │   │                         │  │                                                  ")
print("  │   │         .─────.         │  │   ┌──────────────────────────┬┐                  ")
print("  │   │       ,'       `.       │  │   │                          ││                  ")
print("  │   │      ╱           ╲      │  │   │   ┌────┐                 ││                  ")
print("  │   │     ;             :     │  │   │   │┌──┐│           ┌───┐ ││                  ")
print("  │   │     ;    .   .    :     │  │   │   ││  ││           │   │ ││                  ")
print("  │   │    ;    ( ) ( )    :    │  │   │   ││  ││           └─┬─┘ ││                  ")
print("  │   │    │     ' . '     │    │  │   │   │└──┘├─────────┬┬──┴──┬┴┘                  ")
print("  │   │    │      ( )      │    │  │   │   └────┴─────────┘│     │                    ")
print("  │   │    :       '       ;    │  │   │                   │     │                    ")
print("  │   │     :  ┌───────┐  ;     │  │   │                   │     │                    ")
print("  │   │     :  └───────┘  ;     │  │   │                   │     │                    ")
print("  │   │      ╲           ╱      │  │   │                   └──┬──┘                    ")
print("  │   │       ╲         ╱       │  │   │                      │                       ")
print("  │   │        `.     ,'        │  │   │        .─────────────┴─────────────.         ")
print("  │   │          `─┬─'          │  │   │  _.───'                             `────.   ")
print("  │   │            │            │  │   │ (                                         )  ")
print("  │   │   ┌──────── ────────┐   │  │   │  `─────.                           _.────'   ")
print("  │   │   │                 │   │  │   │         `─────────────────────────'          ")
print("  │   │   │                 │   │  │   │                                              ")
print("  │   │   │                 │   │  │   │                                              ")
print("  │   └───┴─────────────────┴───┘  │   │                                              ")
print("  │                                │   │                                              ")
print("  └────────────────────────────────┘   │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("                                       │                                              ")
print("   . .─────.                           │                                              ")
print("  ( )       ) ─────────────────────────┘                                              ")
print("   ' `─────'                                                                         ")

sleep(15)
clearScreen()

print("Now is the part of the story where I, your loyal and trusty narrator, offer a word of advice.")

sleep(3)
clearScreen()

print("Facebook Live is good for many things.  You can use it to take a live video of your dog.")

sleep(3)
clearScreen()

print("You can use it to livestream your wedding.")

sleep(3)
clearScreen()

print("Even, if you're at Standing Rock or another protest you can use it to livestream resistance to oppression.")

sleep(3)
clearScreen()

print("These are all on good days.")

sleep(15)
clearScreen()

print("What about on bad days?  Remember, there are times that are the worst of times.  Particularly, if you are not catching any fish.")

sleep(6)
clearScreen()

print("┌────────────────────────────────┐                                                 ")
print("│                                │                                                 ")
print("│   ┌─────────────────────────┐  │                                                 ")
print("│   │ ┌─────────────────────┐ │  │                                                 ")
print("│   │ │    Facebook Live    │ │  │                                                 ")
print("│   │ └─────────────────────┘ │  │                                                 ")
print("│   │                         │  │                                                 ")
print("│   │         .─────.         │  │   ┌──────────────────────────┬┐                 ")
print("│   │       ,'       `.       │  │   │                          ││                 ")
print("│   │      ╱           ╲      │  │   │   ┌────┐                 ││                 ")
print("│   │  ││ ;             :     │  │   │   │┌──┐│           ┌───┐ ││                 ")
print("│   │  ││ ;    .   .    :     │  │   │   ││  ││           │   │ ││                 ")
print("│   │  ││;    ( ) ( )    :    │  │   │   ││  ││           └─┬─┘ ││                 ")
print("│   │  │││     ' . '     │    │  │   │   │└──┘├─────────┬┬──┴──┬┴┘                 ")
print("│   │  │││      ( )      │    │  │   │   └────┴─────────┘│     │                   ")
print("│   │  ││:       '       ;    │  │   │                   │     │                   ")
print("│   │  ││ :  ┌───────┐  ;     │  │   │                   │     │                   ")
print("│   │  ││ :  └───────┘  ;     │  │   │                   │     │                   ")
print("│   │┌─┘└─┐╲           ╱      │  │   │                   └──┬──┘                   ")
print("│   ││    │ ╲         ╱       │  │   │                      │                      ")
print("│   ││    │  `.     ,'        │  │   │        .─────────────┴─────────────.        ")
print("│   ││    │    `─┬─'          │  │   │  _.───'                             `────.  ")
print("│   ││    │      │            │  │   │ (                                         ) ")
print("│   ││  ┌─┴───────────────┐   │  │   │  `─────.                           _.────'  ")
print("│   ││  │                 │   │  │   │         `─────────────────────────'         ")
print("│   ││  │                 │   │  │   │                                             ")
print("│   ││  │                 │   │  │   │                                             ")
print("│   └-──┴─────────────────┴───┘  │   │                                             ")
print("│                                │   │                                             ")
print("└────────────────────────────────┘   │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print("                                     │                                             ")
print(" . .─────.                           │                                             ")
print("( )       ) ─────────────────────────┘                                             ")
print(" ' `─────'                                                                         ")

sleep(10)
clearScreen()

print("Jimmy unknowingly became the first man to ever livestream on Facebook something that we in the movie buisness call, 'da, dum, da, dum, moments...'")

sleep(10)
clearScreen()


print(" ┌────────────────────────────────┐                                                                                                 ")
print(" │                                │                                                                                                 ")
print(" │   ┌─────────────────────────┐  │                                                                                                 ")
print(" │   │ ┌─────────────────────┐ │  │                                                                                                 ")
print(" │   │ │    Facebook Live    │ │  │                                                                                                 ")
print(" │   │ └─────────────────────┘ │  │                                                                                                 ")
print(" │   │                         │  │                                                                                                 ")
print(" │   │         .─────.         │  │   ┌──────────────────────────┬┐                                                                 ")
print(" │   │       ,'       `.       │  │   │                          ││                                                                 ")
print(" │   │      ╱           ╲      │  │   │   ┌────┐                 ││                                                                 ")
print(" │   │  ││ ;             :     │  │   │   │┌──┐│           ┌───┐ ││                                                                 ")
print(" │   │  ││ ;    .   .    :     │  │   │   ││  ││           │   │ ││                                                                 ")
print(" │   │  ││;    ( ) ( )    :    │  │   │   ││  ││           └─┬─┘ ││                                                                 ")
print(" │   │  │││     ' . '     │    │  │   │   │└──┘├─────────┬┬──┴──┬┴┘                                                                 ")
print(" │   │  │││      ( )      │    │  │   │   └────┴─────────┘│     │                                                                   ")
print(" │   │  ││:       '       ;    │  │   │                   │     │                                       Λ                           ")
print(" │   │  ││ :  ┌───────┐  ;     │  │   │                   │     │                                      ╱ ╲                          ")
print(" │   │  ││ :  └───────┘  ;     │  │   │                   │     │                                     ╱   ╲                         ")
print(" │   │┌─┘└─┐╲           ╱      │  │   │                   └──┬──┘                                    ╱     ╲                        ")
print(" │   ││    │ ╲         ╱       │  │   │                      │                                      ╱       ╲                 Λ     ")
print(" │   ││    │  `.     ,'        │  │   │        .─────────────┴─────────────.                 .─────────────────────.         ╱ ╲    ")
print(" │   ││    │    `─┬─'          │  │   │  _.───'                             `────.     _.───'                       `────.  ╱   ╲   ")
print(" │   ││    │      │            │  │   │ (                                         )  ,'                                   `.     ╲  ")
print(" │   ││  ┌─┴───────────────┐   │  │   │  `─────.                           _.────'  (                                       )     ▏ ")
print(" │   ││  │                 │   │  │   │         `─────────────────────────'          '─.                                 ,─'     ╱  ")
print(" │   ││  │                 │   │  │   │                                                 `────.                     _.───'   ╲   ╱   ")
print(" │   ││  │                 │   │  │   │                                                      ▕`───────────────────'          ╲ ╱    ")
print(" │   └-──┴─────────────────┴───┘  │   │                                                       ╲   ╱                           V     ")
print(" │                                │   │                                                        ╲ ╱                                  ")
print(" └────────────────────────────────┘   │                                                         V                                   ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("                                      │                                                                                             ")
print("  . .─────.                           │                                                                                             ")
print(" ( )       )-─────────────────────────┘                                                                                             ")
print("  ' `─────'                                                                                                                         ")



sleep(10)
clearScreen()

print("This adventure is just beginning.  What should happen to Jimmy?  The final draft of this will be submitted to the Internets as a choose your own adventure game...")
sleep(10)
clearScreen()
